import Head from 'next/head'
import Link from "next/link";
//Components
import Header from './Header'
import Footer from './Footer'


function Layout(props) {
	const title = "No'fuimo";
  return (
		<>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
			{props.children}
      <Footer />
			</>
  )
}

export default Layout
